server:
  port: 9000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl11
    username: scott
    password: tiger
      
  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 398930234086-14da43k2m0gdbk9r3k12pa87stpuofp2.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          
